# Generated by Django 3.0.6 on 2020-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200717_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imgcourse',
            field=models.ImageField(default=1, upload_to='projects/images'),
            preserve_default=False,
        ),
    ]
