# Generated by Django 3.0.6 on 2020-07-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_imgcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='imgcourse',
        ),
    ]
