# Generated by Django 3.0.6 on 2020-07-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_imgcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='imgurl',
            field=models.ImageField(default=1, upload_to='project/images'),
            preserve_default=False,
        ),
    ]
