# Generated by Django 3.0.6 on 2020-07-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='imgurl',
        ),
        migrations.AddField(
            model_name='course',
            name='catg',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
