# Generated by Django 3.0.6 on 2020-07-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200718_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='catg',
        ),
    ]
